sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.12.2
  - 2.11.11

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer